#ifndef REVIVAL_TRIMESH_H
#define REVIVAL_TRIMESH_H

#include "BaseDefs.h"
#include "Color.h"
#include "Vertex.h"
#include "Face.h"
#include "Edge.h"
#include "Spline.h"
#include "Object.h"
#include "Matrix.h"

#pragma pack(push, 1)

// [172 Bytes]
// Total: [220 Bytes + 84 Bytes per Vertex + 56 Bytes per Face +
//         16 Bytes * (Spline Keys + Hide Keys)]
struct TriMesh
{
    // strided array containing precalculated lighting.
    // uses packed dword BGRA to reduce memory read bandwidth usage
    // was optimized out for sse benefit
    Color			*SL;
    DWord            VIndex;     //Amount of Vertices on Mesh
    DWord            FIndex;     //Amount of Faces on Mesh
    DWord            EIndex;     //Amount of Edges on Mesh
    Vertex         * Verts;      //Vertex List
    Face           * Faces;      //Face List
    Edge           * Edges;      //Edge List
    Spline           Pos;        //Position Track Spline
    Spline           Scale;      //Scale Track Spline
    Spline           Rotate;     //Orientation Track Spline
    ObjectStatus   * Status;     //Hide Track (crap)
    ObjectStatus   * CurStat;    //Current Hide status
    Vector           IPos;       //Interpolated Position
    Vector           IScale;     //Interpolated Scale
    Quaternion       IRot;       //Interpolated Orientation (Quaternion)
    Matrix           RotMat;     //Interpolated Orientation (Matrix)
    Vector		     Heading;    // Generated by Position Track spline for meshes with the Align to path flag.
    Vector           BSphereCtr; // Bounding Sphere Center.
    Vector           BSphereScreenPos; // Bounding Sphere Center.
    float			 BSphereRadius; // Bounding Sphere Radius.
    float            BSphereRad; // Bounding Sphere Radius, squared. kept for backward compatibility until pipeline code is updated
    DWord            Flags;

    // this is a temporary hack and will be removed in the future
    dword			 SortPriorityBias; // '1' value causes object to always be rendered first

    TriMesh      * Next;
    TriMesh      * Prev;
};

#pragma pack(pop)

#endif //REVIVAL_TRIMESH_H
