;=====================================================================
; FMOD FSOUND_REVERB_PRESETS
; Translated to assembly by Ricardo Santos
; dxantos@yahoo.com
;=====================================================================

.586
.model flat, stdcall
include fmod.inc

;---------------------------------------------------------------------
.const
;---------------------------------------------------------------------
FSOUND_PRESET_GENERIC			FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_GENERIC,0.5f, 1.493f,  0.5f>
FSOUND_PRESET_PADDEDCELL      	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_PADDEDCELL,0.25f, 0.1f, 0.0f>
FSOUND_PRESET_ROOM            	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_ROOM,0.417f, 0.4f, 0.666f>
FSOUND_PRESET_BATHROOM        	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_BATHROOM,0.653f, 1.499f, 0.166f>
FSOUND_PRESET_LIVINGROOM      	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_LIVINGROOM,0.208f, 0.478f, 0.0f>
FSOUND_PRESET_STONEROOM       	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_STONEROOM,0.5f, 2.309f, 0.888f>
FSOUND_PRESET_AUDITORIUM      	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_AUDITORIUM,0.403f, 4.279f, 0.5f>
FSOUND_PRESET_CONCERTHALL     	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_CONCERTHALL,0.5f, 3.961f, 0.5f>
FSOUND_PRESET_CAVE            	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_CAVE,0.5f, 2.886f, 1.304f>
FSOUND_PRESET_ARENA           	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_ARENA,0.361f, 7.284f, 0.332f>
FSOUND_PRESET_HANGAR          	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_HANGAR,0.5f, 10.0f, 0.3f>
FSOUND_PRESET_CARPETEDHALLWAY 	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_CARPETEDHALLWAY,0.153f, 0.259f, 2.0f>
FSOUND_PRESET_HALLWAY         	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_HALLWAY,0.361f, 1.493f, 0.0f>
FSOUND_PRESET_STONECORRIDOR   	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_STONECORRIDOR,0.444f, 2.697f, 0.638f>
FSOUND_PRESET_ALLEY           	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_ALLEY,0.25f,  1.752f, 0.776f>
FSOUND_PRESET_FOREST          	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_FOREST,0.111f, 3.145f, 0.472f>
FSOUND_PRESET_CITY            	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_CITY,0.111f, 2.767f, 0.224f>
FSOUND_PRESET_MOUNTAINS       	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_MOUNTAINS,0.194f, 7.841f,  0.472f>
FSOUND_PRESET_QUARRY          	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_QUARRY,1.0f, 1.499f, 0.5f>
FSOUND_PRESET_PLAIN           	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_PLAIN,0.097f, 2.767f, 0.224f>
FSOUND_PRESET_PARKINGLOT      	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_PARKINGLOT,0.208f, 1.652f, 1.5f>
FSOUND_PRESET_SEWERPIPE       	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_SEWERPIPE,0.652f, 2.886f, 0.25f>
FSOUND_PRESET_UNDERWATER      	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_UNDERWATER,1.0f, 1.499f, 0.0f>
FSOUND_PRESET_DRUGGED         	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_DRUGGED,0.875f, 8.392f,  1.388f>
FSOUND_PRESET_DIZZY           	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_DIZZY,0.139f, 17.234f, 0.666f>
FSOUND_PRESET_PSYCHOTIC       	FSOUND_REVERB_PRESET<FSOUND_ENVIRONMENT_PSYCHOTIC,0.486f, 7.563f, 0.806f>

;---------------------------------------------------------------------
.code
;---------------------------------------------------------------------

	align 4
;=====================================================================
FSOUND_Reverb_SetEnvironmentPreset proc near public,
	preset:dword
;=====================================================================
;{
	mov edx, preset

	invoke FSOUND_Reverb_SetEnvironment, [edx], [edx + 4], [edx + 8], [edx + 12]
	ret
;}
FSOUND_Reverb_SetEnvironmentPreset endp

end
